export enum AuthErrorType {
  UNIQUE_VIOLATION = "UNIQUE_VIOLATION",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_STRING = "INVALID_STRING",
  PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT",
}
